// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44c4eqJGnUMU2mknEg1uPNi8p1j3aqfY',
    appId: '1:1050727432684:web:57b99cc42f884a6fcf40c9',
    messagingSenderId: '1050727432684',
    projectId: 'roddkm-d0b21',
    authDomain: 'roddkm-d0b21.firebaseapp.com',
    storageBucket: 'roddkm-d0b21.appspot.com',
    measurementId: 'G-1KFJ5MKLHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Akar4pPKc3kKKlQdd8wE34ReEYjBU8M',
    appId: '1:1050727432684:android:eb1e4ce8133c68d7cf40c9',
    messagingSenderId: '1050727432684',
    projectId: 'roddkm-d0b21',
    storageBucket: 'roddkm-d0b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIPHfORWUTpJ1AONwV3VuSzq9wEQA_q08',
    appId: '1:1050727432684:ios:de98c75a7cf8b432cf40c9',
    messagingSenderId: '1050727432684',
    projectId: 'roddkm-d0b21',
    storageBucket: 'roddkm-d0b21.appspot.com',
    iosClientId: '1050727432684-r32ik0kqr0gie0mnksm2g6phi39297cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalgradproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIPHfORWUTpJ1AONwV3VuSzq9wEQA_q08',
    appId: '1:1050727432684:ios:de98c75a7cf8b432cf40c9',
    messagingSenderId: '1050727432684',
    projectId: 'roddkm-d0b21',
    storageBucket: 'roddkm-d0b21.appspot.com',
    iosClientId: '1050727432684-r32ik0kqr0gie0mnksm2g6phi39297cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalgradproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC44c4eqJGnUMU2mknEg1uPNi8p1j3aqfY',
    appId: '1:1050727432684:web:3d90940501329dc0cf40c9',
    messagingSenderId: '1050727432684',
    projectId: 'roddkm-d0b21',
    authDomain: 'roddkm-d0b21.firebaseapp.com',
    storageBucket: 'roddkm-d0b21.appspot.com',
    measurementId: 'G-4E2Y1XXCBD',
  );

}